version: '3.4'

networks:
    dev:
        driver: bridge
        
services:
    warehouses-postgres:
        image: postgres:latest
        container_name: warehouses-postgres
        environment:
            - POSTGRES_DB=WarehousesDb
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            
        ports:
            - "5433:5432"
        restart: always
        volumes:
            - ./DockerDbScripts:/docker-entrypoint-initdb.d
        networks:
            - dev
            
    warehouses_sample:
        image: docker.io/library/warehouses_docker
        depends_on:
            - "warehouses-postgres"
        container_name: warehouses_sample
        ports: 
            - "5000:8080"
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - ConnectionStrings__DefaultConnection=User Id=postgres;Password=admin;Server=warehouses-postgres;Port=5432;Database=WarehousesDb; Pooling=true;
            - ASPNETCORE_URLS=http://+:8080
        networks:
            - dev
            
volumes:
    app_data: